config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :courses
   root 'courses#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: [:show, :edit, :update, :destroy]

  # GET /courses
  # GET /courses.json
  def index
    @courses = Course.all
  end

  # GET /courses/1
  # GET /courses/1.json
  def show
  end

  # GET /courses/new
  def new
    @course = Course.new
  end

  # GET /courses/1/edit
  def edit
  end

  # POST /courses
  # POST /courses.json
  def create
    @course = Course.new(course_params)

    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, notice: 'Course was successfully created.' }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { render :new }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1
  # PATCH/PUT /courses/1.json
  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to @course, notice: 'Course was successfully updated.' }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1
  # DELETE /courses/1.json
  def destroy
    @course.destroy
    respond_to do |format|
      format.html { redirect_to courses_url, notice: 'Course was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def course_params
      params.require(:course).permit(:Name, :SI_LEADER, :Department, :Venue, :Session_times)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/courses/_form.html.erb
<%= form_for(course) do |f| %>
  <% if course.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(course.errors.count, "error") %> prohibited this course from being saved:</h2>

      <ul>
      <% course.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Name %>
    <%= f.text_field :Name %>
  </div>

  <div class="field">
    <%= f.label :SI_LEADER %>
    <%= f.text_field :SI_LEADER %>
  </div>

  <div class="field">
    <%= f.label :Department %>
    <%= f.text_field :Department %>
  </div>

  <div class="field">
    <%= f.label :Venue %>
    <%= f.text_field :Venue %>
  </div>

  <div class="field">
    <%= f.label :Session_times %>
    <%= f.text_area :Session_times %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/courses/edit.html.erb
<div class = "col-md-8 col-md-offset-2" >
	<h1>Editing Course</h1>

	<%= render 'form', course: @course %>

	<%= link_to 'Show', @course %> |
	<%= link_to 'Back', courses_path %>
</div>

app/views/courses/index.html.erb
	<p id="notice"><%= notice %></p>
	<h1>Courses</h1>
	<% @courses.each do |course| %>
	  <div class = "col-md-4">
	    <h2><%= course.Name %></h2>
	    <%= link_to 'VIEW ARTICLE', course %>
	    <%= link_to 'DELETE ARTICLE', course, method: :delete, data: { confirm: 'Are you sure?', class: "btn btn-default" } %> 
	  </div>
	<% end %>

	<br/>
	<br/>
	<br/>

app/views/courses/new.html.erb
 <div class = "col-md-8 col-md-offset-2" >
	<h1>New Course</h1>

	<%= render 'form', course: @course %>

	<%= link_to 'Back', courses_path %>
</div>

app/views/courses/show.html.erb
 <div class = "col-md-8 col-md-offset-2" >
    <p id="notice"><%= notice %></p>
    <p>
      <strong>Name:</strong>
      <%= @course.Name %>
    </p>

    <p>
      <strong>Si leader:</strong>
      <%= @course.SI_LEADER %>
    </p>

    <p>
      <strong>Department:</strong>
      <%= @course.Department %>
    </p>

    <p>
      <strong>Venue:</strong>
      <%= @course.Venue %>
    </p>

    <p>
      <strong>Session times:</strong>
      <%= @course.Session_times %>
    </p>

    <%= link_to 'Edit', edit_course_path(@course) %> |
    <%= link_to 'Back', courses_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
   

   <div class = "navbar navbar-default">
     <div class="container"> 
            <div class="navbar-header" >
               <%=link_to "HOME" ,root_path ,class: "navbar-brand"%>
                <ul class = "nav navbar-nav">
              <li><%= link_to "Sign Up" , new_user_registration_path %></li>
            </ul>
            <ul class = "nav navbar-nav">
           
             <li><%= link_to "Sign Out" , destroy_user_session_path , method: :delete%></li>
            <%else%>
             <li><%= link_to "Log In" , user_session_path %></li>
                   
            </ul>
            
            </div>
            
              <ul class = "nav navbar-nav navbar-right">
              <li><%= link_to 'ARTICLES', new_course_path , class: "btn btn-default"%></li>
              <%if user_signed_in?%>
                <li><%= link_to 'New Course', new_course_path , class: "btn btn-default"%></li>
              <%end%>
              </ul>
         
        </div>
    </div>

   <p class="notice"><%= notice %></p>
   <p class="alert"><%= alert %></p>
   <div class="container">
    <%= yield %>
    </div>
  </body>
</html>